// GENERATED by scripts/fetch-circuit-photos.ts — do not edit by hand.
// Refresh with: npm run fetch-circuit-photos
// Official racehub circuit photography, keyed by circuit_short_name.
// Circuits absent here (no photo upstream) fall back to line art.

export const CIRCUIT_PHOTOS: Record<string, string> = {
  "Melbourne": "/media/circuit-photos/melbourne.jpg",
  "Shanghai": "/media/circuit-photos/shanghai.jpg",
  "Suzuka": "/media/circuit-photos/suzuka.jpg",
  "Sakhir": "/media/circuit-photos/sakhir.jpg",
  "Jeddah": "/media/circuit-photos/jeddah.jpg",
  "Miami": "/media/circuit-photos/miami.jpg",
  "Montreal": "/media/circuit-photos/montreal.jpg",
  "Monte Carlo": "/media/circuit-photos/monte-carlo.jpg",
  "Catalunya": "/media/circuit-photos/catalunya.jpg",
  "Spielberg": "/media/circuit-photos/spielberg.jpg",
  "Silverstone": "/media/circuit-photos/silverstone.jpg",
  "Spa-Francorchamps": "/media/circuit-photos/spa-francorchamps.jpg",
  "Hungaroring": "/media/circuit-photos/hungaroring.jpg",
  "Zandvoort": "/media/circuit-photos/zandvoort.jpg",
  "Monza": "/media/circuit-photos/monza.jpg",
  "Baku": "/media/circuit-photos/baku.jpg",
  "Singapore": "/media/circuit-photos/singapore.jpg",
  "Austin": "/media/circuit-photos/austin.jpg",
  "Mexico City": "/media/circuit-photos/mexico-city.jpg",
  "Interlagos": "/media/circuit-photos/interlagos.jpg",
  "Las Vegas": "/media/circuit-photos/las-vegas.jpg",
  "Lusail": "/media/circuit-photos/lusail.jpg",
  "Yas Marina Circuit": "/media/circuit-photos/yas-marina-circuit.jpg"
}

export const circuitPhoto = (circuitShortName: string): string | null =>
  CIRCUIT_PHOTOS[circuitShortName] ?? null
