// GENERATED by scripts/fetch-f1-media.ts — do not edit by hand.
// Refresh with: npm run fetch-media

export const DRIVER_IMAGES: Record<string, string> = {
  "RUS": "/media/drivers/RUS.webp",
  "ANT": "/media/drivers/ANT.webp",
  "LEC": "/media/drivers/LEC.webp",
  "HAM": "/media/drivers/HAM.webp",
  "NOR": "/media/drivers/NOR.webp",
  "PIA": "/media/drivers/PIA.webp",
  "OCO": "/media/drivers/OCO.webp",
  "BEA": "/media/drivers/BEA.webp",
  "VER": "/media/drivers/VER.webp",
  "HAD": "/media/drivers/HAD.webp",
  "LAW": "/media/drivers/LAW.webp",
  "LIN": "/media/drivers/LIN.webp",
  "GAS": "/media/drivers/GAS.webp",
  "COL": "/media/drivers/COL.webp",
  "HUL": "/media/drivers/HUL.webp",
  "BOR": "/media/drivers/BOR.webp",
  "SAI": "/media/drivers/SAI.webp",
  "ALB": "/media/drivers/ALB.webp",
  "PER": "/media/drivers/PER.webp",
  "BOT": "/media/drivers/BOT.webp",
  "ALO": "/media/drivers/ALO.webp",
  "STR": "/media/drivers/STR.webp"
}

export const CAR_IMAGES: Record<string, string> = {
  "red-bull-racing": "/media/cars/red-bull-racing.webp",
  "ferrari": "/media/cars/ferrari.webp",
  "scuderia-ferrari": "/media/cars/ferrari.webp",
  "mclaren": "/media/cars/mclaren.webp",
  "mercedes": "/media/cars/mercedes.webp",
  "mercedes-amg-petronas-f1-team": "/media/cars/mercedes.webp",
  "aston-martin": "/media/cars/aston-martin.webp",
  "aston-martin-aramco-f1-team": "/media/cars/aston-martin.webp",
  "alpine": "/media/cars/alpine.webp",
  "bwt-alpine-f1-team": "/media/cars/alpine.webp",
  "williams": "/media/cars/williams.webp",
  "williams-racing": "/media/cars/williams.webp",
  "racing-bulls": "/media/cars/racing-bulls.webp",
  "haas-f1-team": "/media/cars/haas.webp",
  "haas": "/media/cars/haas.webp",
  "audi": "/media/cars/audi.webp",
  "audi-f1-team": "/media/cars/audi.webp",
  "cadillac": "/media/cars/cadillac.webp",
  "cadillac-formula-one-team": "/media/cars/cadillac.webp"
}

// Full-resolution renders for the team-detail glide (w_3392 — the 1280
// renditions are visibly soft at glide scale).
export const CAR_IMAGES_HI: Record<string, string> = {
  "red-bull-racing": "/media/cars-hi/red-bull-racing.webp",
  "ferrari": "/media/cars-hi/ferrari.webp",
  "scuderia-ferrari": "/media/cars-hi/ferrari.webp",
  "mclaren": "/media/cars-hi/mclaren.webp",
  "mercedes": "/media/cars-hi/mercedes.webp",
  "mercedes-amg-petronas-f1-team": "/media/cars-hi/mercedes.webp",
  "aston-martin": "/media/cars-hi/aston-martin.webp",
  "aston-martin-aramco-f1-team": "/media/cars-hi/aston-martin.webp",
  "alpine": "/media/cars-hi/alpine.webp",
  "bwt-alpine-f1-team": "/media/cars-hi/alpine.webp",
  "williams": "/media/cars-hi/williams.webp",
  "williams-racing": "/media/cars-hi/williams.webp",
  "racing-bulls": "/media/cars-hi/racing-bulls.webp",
  "haas-f1-team": "/media/cars-hi/haas.webp",
  "haas": "/media/cars-hi/haas.webp",
  "audi": "/media/cars-hi/audi.webp",
  "audi-f1-team": "/media/cars-hi/audi.webp",
  "cadillac": "/media/cars-hi/cadillac.webp",
  "cadillac-formula-one-team": "/media/cars-hi/cadillac.webp"
}

export const TEAM_LOGO_IMAGES: Record<string, string> = {
  "mclaren": "/media/teams/mclaren-logo.svg",
  "ferrari": "/media/teams/ferrari-logo.svg",
  "scuderia-ferrari": "/media/teams/ferrari-logo.svg",
  "red-bull-racing": "/media/teams/red-bull-racing-logo.svg",
  "oracle-red-bull-racing": "/media/teams/red-bull-racing-logo.svg",
  "mercedes": "/media/teams/mercedes-logo.svg",
  "mercedes-amg-petronas-f1-team": "/media/teams/mercedes-logo.svg",
  "aston-martin": "/media/teams/aston-martin-logo.png",
  "aston-martin-aramco-f1-team": "/media/teams/aston-martin-logo.png",
  "alpine": "/media/teams/alpine-logo.png",
  "bwt-alpine-f1-team": "/media/teams/alpine-logo.png",
  "williams": "/media/teams/williams-logo.svg",
  "williams-racing": "/media/teams/williams-logo.svg",
  "racing-bulls": "/media/teams/racing-bulls-logo.svg",
  "haas-f1-team": "/media/teams/haas-logo.svg",
  "haas": "/media/teams/haas-logo.svg",
  "audi": "/media/teams/audi-logo.svg",
  "audi-f1-team": "/media/teams/audi-logo.svg",
  "cadillac": "/media/teams/cadillac-logo.svg",
  "cadillac-formula-one-team": "/media/teams/cadillac-logo.svg"
}

// keyed by meeting_key (stringified) — collision-proof for countries that
// host more than one round
export const CIRCUIT_IMAGES_BY_MEETING: Record<string, string> = {
  "1279": "/media/circuits/australia.png",
  "1280": "/media/circuits/china.png",
  "1281": "/media/circuits/japan.png",
  "1282": "/media/circuits/bahrain.png",
  "1283": "/media/circuits/saudi-arabia.png",
  "1284": "/media/circuits/united-states.png",
  "1285": "/media/circuits/canada.png",
  "1286": "/media/circuits/monaco.png",
  "1288": "/media/circuits/austria.png",
  "1289": "/media/circuits/united-kingdom.png",
  "1290": "/media/circuits/belgium.png",
  "1291": "/media/circuits/hungary.png",
  "1292": "/media/circuits/netherlands.png",
  "1293": "/media/circuits/italy.png",
  "1294": "/media/circuits/meeting-1294.png",
  "1295": "/media/circuits/azerbaijan.png",
  "1296": "/media/circuits/singapore.png",
  "1297": "/media/circuits/meeting-1297.png",
  "1298": "/media/circuits/mexico.png",
  "1299": "/media/circuits/brazil.png",
  "1300": "/media/circuits/meeting-1300.png",
  "1301": "/media/circuits/qatar.png",
  "1302": "/media/circuits/united-arab-emirates.png",
  "1304": "/media/circuits/bahrain.png",
  "1305": "/media/circuits/bahrain.png",
  "1308": "/media/circuits/bahrain.png"
}

// legacy country_name map — first meeting per country
export const CIRCUIT_IMAGES: Record<string, string> = {
  "Bahrain": "/media/circuits/bahrain.png",
  "Australia": "/media/circuits/australia.png",
  "China": "/media/circuits/china.png",
  "Japan": "/media/circuits/japan.png",
  "Saudi Arabia": "/media/circuits/saudi-arabia.png",
  "United States": "/media/circuits/united-states.png",
  "Canada": "/media/circuits/canada.png",
  "Monaco": "/media/circuits/monaco.png",
  "Austria": "/media/circuits/austria.png",
  "United Kingdom": "/media/circuits/united-kingdom.png",
  "Belgium": "/media/circuits/belgium.png",
  "Hungary": "/media/circuits/hungary.png",
  "Netherlands": "/media/circuits/netherlands.png",
  "Italy": "/media/circuits/italy.png",
  "Spain": "/media/circuits/meeting-1294.png",
  "Azerbaijan": "/media/circuits/azerbaijan.png",
  "Singapore": "/media/circuits/singapore.png",
  "Mexico": "/media/circuits/mexico.png",
  "Brazil": "/media/circuits/brazil.png",
  "Qatar": "/media/circuits/qatar.png",
  "United Arab Emirates": "/media/circuits/united-arab-emirates.png"
}

export const driverImage = (acronym: string): string | null =>
  DRIVER_IMAGES[acronym?.toUpperCase()] ?? null

export const carImage = (teamSlug: string): string | null => CAR_IMAGES[teamSlug] ?? null

export const carImageHi = (teamSlug: string): string | null =>
  CAR_IMAGES_HI[teamSlug] ?? CAR_IMAGES[teamSlug] ?? null

export const teamLogoImage = (teamSlug: string): string | null =>
  TEAM_LOGO_IMAGES[teamSlug] ?? null

export const circuitImage = (countryName: string): string | null =>
  CIRCUIT_IMAGES[countryName] ?? null

// Meetings whose upstream circuit_image is known to be WRONG. openf1 serves
// the Sakhir track icon for the Bahrain GP replacement round held in Kuala
// Lumpur (meeting 1308) — byte-identical URL to the cancelled round's. A
// factually wrong circuit outline is worse than none, so this round renders
// without art until F1 publishes a Kuala Lumpur icon.
export const CIRCUIT_ART_SUPPRESSED: ReadonlySet<string> = new Set(['1308'])

/**
 * Circuit art for a meeting — per-meeting ONLY, deliberately with no
 * country fallback. Falling back to the country map hands a round its
 * neighbour's outline: Barcelona's own icon 404s upstream, so a fallback
 * would draw Madrid's circuit on the Barcelona round. No art beats wrong
 * art; a missing icon degrades to empty space by design.
 */
export const circuitImageForMeeting = (
  meeting: { meeting_key: number; country_name: string }
): string | null => {
  const key = String(meeting.meeting_key)
  if (CIRCUIT_ART_SUPPRESSED.has(key)) return null
  return CIRCUIT_IMAGES_BY_MEETING[key] ?? null
}
