// GENERATED by scripts/fetch-f1-media.ts — do not edit by hand.
// Refresh with: npm run fetch-media

export const DRIVER_IMAGES: Record<string, string> = {
  "RUS": "/media/drivers/RUS.webp",
  "ANT": "/media/drivers/ANT.webp",
  "LEC": "/media/drivers/LEC.webp",
  "HAM": "/media/drivers/HAM.webp",
  "NOR": "/media/drivers/NOR.webp",
  "PIA": "/media/drivers/PIA.webp",
  "OCO": "/media/drivers/OCO.webp",
  "BEA": "/media/drivers/BEA.webp",
  "VER": "/media/drivers/VER.webp",
  "HAD": "/media/drivers/HAD.webp",
  "LAW": "/media/drivers/LAW.webp",
  "LIN": "/media/drivers/LIN.webp",
  "GAS": "/media/drivers/GAS.webp",
  "COL": "/media/drivers/COL.webp",
  "HUL": "/media/drivers/HUL.webp",
  "BOR": "/media/drivers/BOR.webp",
  "SAI": "/media/drivers/SAI.webp",
  "ALB": "/media/drivers/ALB.webp",
  "PER": "/media/drivers/PER.webp",
  "BOT": "/media/drivers/BOT.webp",
  "ALO": "/media/drivers/ALO.webp",
  "STR": "/media/drivers/STR.webp"
}

export const CAR_IMAGES: Record<string, string> = {
  "red-bull-racing": "/media/cars/red-bull-racing.webp",
  "ferrari": "/media/cars/ferrari.webp",
  "scuderia-ferrari": "/media/cars/scuderia-ferrari.webp",
  "mclaren": "/media/cars/mclaren.webp",
  "mercedes": "/media/cars/mercedes.webp",
  "mercedes-amg-petronas-f1-team": "/media/cars/mercedes-amg-petronas-f1-team.webp",
  "aston-martin": "/media/cars/aston-martin.webp",
  "aston-martin-aramco-f1-team": "/media/cars/aston-martin-aramco-f1-team.webp",
  "alpine": "/media/cars/alpine.webp",
  "bwt-alpine-f1-team": "/media/cars/bwt-alpine-f1-team.webp",
  "williams": "/media/cars/williams.webp",
  "williams-racing": "/media/cars/williams-racing.webp",
  "racing-bulls": "/media/cars/racing-bulls.webp",
  "haas-f1-team": "/media/cars/haas-f1-team.webp",
  "haas": "/media/cars/haas.webp",
  "audi": "/media/cars/audi.webp",
  "audi-f1-team": "/media/cars/audi-f1-team.webp",
  "cadillac": "/media/cars/cadillac.webp",
  "cadillac-formula-one-team": "/media/cars/cadillac-formula-one-team.webp"
}

export const TEAM_LOGO_IMAGES: Record<string, string> = {
  "mclaren": "/media/teams/mclaren-logo.svg",
  "ferrari": "/media/teams/ferrari-logo.svg",
  "scuderia-ferrari": "/media/teams/scuderia-ferrari-logo.svg",
  "red-bull-racing": "/media/teams/red-bull-racing-logo.svg",
  "oracle-red-bull-racing": "/media/teams/oracle-red-bull-racing-logo.svg",
  "mercedes": "/media/teams/mercedes-logo.svg",
  "mercedes-amg-petronas-f1-team": "/media/teams/mercedes-amg-petronas-f1-team-logo.svg",
  "aston-martin": "/media/teams/aston-martin-logo.png",
  "aston-martin-aramco-f1-team": "/media/teams/aston-martin-aramco-f1-team-logo.png",
  "alpine": "/media/teams/alpine-logo.png",
  "bwt-alpine-f1-team": "/media/teams/bwt-alpine-f1-team-logo.png",
  "williams": "/media/teams/williams-logo.svg",
  "williams-racing": "/media/teams/williams-racing-logo.svg",
  "racing-bulls": "/media/teams/racing-bulls-logo.svg",
  "haas-f1-team": "/media/teams/haas-f1-team-logo.svg",
  "haas": "/media/teams/haas-logo.svg",
  "audi": "/media/teams/audi-logo.svg",
  "audi-f1-team": "/media/teams/audi-f1-team-logo.svg",
  "cadillac": "/media/teams/cadillac-logo.svg",
  "cadillac-formula-one-team": "/media/teams/cadillac-formula-one-team-logo.svg"
}

// keyed by country_name as it appears in the calendar data
export const CIRCUIT_IMAGES: Record<string, string> = {
  "Bahrain": "/media/circuits/bahrain.png",
  "Australia": "/media/circuits/australia.png",
  "China": "/media/circuits/china.png",
  "Japan": "/media/circuits/japan.png",
  "Saudi Arabia": "/media/circuits/saudi-arabia.png",
  "United States": "/media/circuits/united-states.png",
  "Canada": "/media/circuits/canada.png",
  "Monaco": "/media/circuits/monaco.png",
  "Austria": "/media/circuits/austria.png",
  "United Kingdom": "/media/circuits/united-kingdom.png",
  "Belgium": "/media/circuits/belgium.png",
  "Hungary": "/media/circuits/hungary.png",
  "Netherlands": "/media/circuits/netherlands.png",
  "Italy": "/media/circuits/italy.png",
  "Azerbaijan": "/media/circuits/azerbaijan.png",
  "Singapore": "/media/circuits/singapore.png",
  "Mexico": "/media/circuits/mexico.png",
  "Brazil": "/media/circuits/brazil.png",
  "Qatar": "/media/circuits/qatar.png",
  "United Arab Emirates": "/media/circuits/united-arab-emirates.png"
}

export const driverImage = (acronym: string): string | null =>
  DRIVER_IMAGES[acronym?.toUpperCase()] ?? null

export const carImage = (teamSlug: string): string | null => CAR_IMAGES[teamSlug] ?? null

export const teamLogoImage = (teamSlug: string): string | null =>
  TEAM_LOGO_IMAGES[teamSlug] ?? null

export const circuitImage = (countryName: string): string | null =>
  CIRCUIT_IMAGES[countryName] ?? null
