// GENERATED by scripts/sync-roster.ts — re-run when the roster changes.
//
// The LAST-KNOWN-GOOD slug list. generateStaticParams falls back to this
// when the season bundle it reads is empty or implausible, so a poisoned
// data source (bot-challenge HTML, an SSO redirect, a rate-limited
// fallback) degrades to slightly stale slugs instead of silently
// prerendering nothing. ISR still fetches fresh data at request time — only
// the SET OF PAGES comes from here.
//
// Snapshot taken: 2026-08-06

export const FALLBACK_DRIVER_ACRONYMS: readonly string[] = [
  "ALB",
  "ALO",
  "ANT",
  "BEA",
  "BOR",
  "BOT",
  "COL",
  "GAS",
  "HAD",
  "HAM",
  "HUL",
  "LAW",
  "LEC",
  "LIN",
  "NOR",
  "OCO",
  "PER",
  "PIA",
  "RUS",
  "SAI",
  "STR",
  "VER"
]

export const FALLBACK_TEAM_SLUGS: readonly string[] = [
  "alpine",
  "aston-martin",
  "audi",
  "cadillac",
  "ferrari",
  "haas-f1-team",
  "mclaren",
  "mercedes",
  "racing-bulls",
  "red-bull-racing",
  "williams"
]
