// GENERATED by scripts/fetch-track-lines.ts — do not edit by hand.
// Refresh with: npm run fetch-tracks
// Real 2025 fastest-lap racing lines, keyed by circuit_short_name.

export const TRACK_LINES: Record<string, string> = {
  "Melbourne": "/media/tracks/melbourne.json",
  "Shanghai": "/media/tracks/shanghai.json",
  "Suzuka": "/media/tracks/suzuka.json",
  "Sakhir": "/media/tracks/sakhir.json",
  "Jeddah": "/media/tracks/jeddah.json",
  "Miami": "/media/tracks/miami.json",
  "Montreal": "/media/tracks/montreal.json",
  "Monte Carlo": "/media/tracks/monte-carlo.json",
  "Catalunya": "/media/tracks/catalunya.json",
  "Spielberg": "/media/tracks/spielberg.json",
  "Silverstone": "/media/tracks/silverstone.json",
  "Spa-Francorchamps": "/media/tracks/spa-francorchamps.json",
  "Hungaroring": "/media/tracks/hungaroring.json",
  "Zandvoort": "/media/tracks/zandvoort.json",
  "Monza": "/media/tracks/monza.json",
  "Singapore": "/media/tracks/singapore.json",
  "Austin": "/media/tracks/austin.json",
  "Mexico City": "/media/tracks/mexico-city.json",
  "Interlagos": "/media/tracks/interlagos.json",
  "Las Vegas": "/media/tracks/las-vegas.json",
  "Lusail": "/media/tracks/lusail.json",
  "Yas Marina Circuit": "/media/tracks/yas-marina-circuit.json"
}

export const trackLine = (circuitShortName: string): string | null =>
  TRACK_LINES[circuitShortName] ?? null
