/**
 * Fetch one official circuit hero photo per 2026 round from
 * media.formula1.com's racehub header set into public/media/circuit-photos/,
 * and generate lib/circuit-photos-manifest.ts keyed by circuit_short_name.
 * Re-run any time with: npm run fetch-circuit-photos
 *
 * Circuits with no photo on the CDN (Madring — new for 2026) are simply
 * absent from the manifest: the NOW backdrop falls back to the carbon
 * line-art icon for those, so misses here never break anything.
 */
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'

const ROOT = path.join(__dirname, '..')
const OUT = path.join(ROOT, 'public', 'media', 'circuit-photos')

// circuit_short_name -> racehub photo name (availability probed 2026-07-19;
// Madring verified absent upstream)
const RACEHUB_NAMES: Record<string, string> = {
  'Melbourne': 'Australia',
  'Shanghai': 'China',
  'Suzuka': 'Japan',
  'Sakhir': 'Bahrain',
  'Jeddah': 'Saudi_Arabia',
  'Miami': 'Miami',
  'Montreal': 'Canada',
  'Monte Carlo': 'Monaco',
  'Catalunya': 'Spain',
  'Spielberg': 'Austria',
  'Silverstone': 'Great Britain',
  'Spa-Francorchamps': 'Belgium',
  'Hungaroring': 'Hungary',
  'Zandvoort': 'Netherlands',
  'Monza': 'Italy',
  'Baku': 'Azerbaijan',
  'Singapore': 'Singapore',
  'Austin': 'USA',
  'Mexico City': 'Mexico',
  'Interlagos': 'Brazil',
  'Las Vegas': 'Las Vegas',
  'Lusail': 'Qatar',
  'Yas Marina Circuit': 'Abu Dhabi',
}

const slug = (s: string) =>
  s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')

const url = (name: string) =>
  `https://media.formula1.com/image/upload/f_auto,c_limit,w_1600,q_auto/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/${encodeURIComponent(name)}.jpg`

async function main() {
  await mkdir(OUT, { recursive: true })
  const paths: Record<string, string> = {}
  const missing: string[] = []
  for (const [circuit, name] of Object.entries(RACEHUB_NAMES)) {
    try {
      const res = await fetch(url(name), { headers: { 'User-Agent': 'lights-out-site/1.0' } })
      if (!res.ok) {
        console.log(`MISS ${circuit} (${res.status})`)
        missing.push(circuit)
        continue
      }
      const buf = Buffer.from(await res.arrayBuffer())
      if (buf.length < 10000) {
        console.log(`MISS ${circuit} (tiny ${buf.length}b)`)
        missing.push(circuit)
        continue
      }
      const file = `${slug(circuit)}.jpg`
      await writeFile(path.join(OUT, file), buf)
      paths[circuit] = `/media/circuit-photos/${file}`
      console.log(`OK   ${circuit} (${Math.round(buf.length / 1024)}KB)`)
    } catch (err) {
      console.log(`MISS ${circuit} (${(err as Error).message})`)
      missing.push(circuit)
    }
    await new Promise((r) => setTimeout(r, 200))
  }

  const manifest = `// GENERATED by scripts/fetch-circuit-photos.ts — do not edit by hand.
// Refresh with: npm run fetch-circuit-photos
// Official racehub circuit photography, keyed by circuit_short_name.
// Circuits absent here (no photo upstream) fall back to line art.

export const CIRCUIT_PHOTOS: Record<string, string> = ${JSON.stringify(paths, null, 2)}

export const circuitPhoto = (circuitShortName: string): string | null =>
  CIRCUIT_PHOTOS[circuitShortName] ?? null
`
  await writeFile(path.join(ROOT, 'lib', 'circuit-photos-manifest.ts'), manifest)
  console.log(`\nTOTAL: ${Object.keys(paths).length}/${Object.keys(RACEHUB_NAMES).length} photos`)
  if (missing.length) console.log('missing:', missing.join(', '))
}

main()
