/**
 * Fetch one official circuit hero photo per 2026 round from
 * Formula 1's racehub headers and circuit galleries into public/media/circuit-photos/,
 * and generate lib/circuit-photos-manifest.ts keyed by circuit_short_name.
 * Re-run any time with: npm run fetch-circuit-photos
 *
 * Refresh selected circuits without re-downloading the rest:
 * npm run fetch-circuit-photos -- Madring "Kuala Lumpur"
 * Unknown future circuits fall back to line art in both home and Schedule.
 */
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { CIRCUIT_PHOTOS } from '../lib/circuit-photos-manifest'

const ROOT = path.join(__dirname, '..')
const OUT = path.join(ROOT, 'public', 'media', 'circuit-photos')

// circuit_short_name -> racehub photo name
const RACEHUB_NAMES: Record<string, string> = {
  'Melbourne': 'Australia',
  'Shanghai': 'China',
  'Suzuka': 'Japan',
  'Sakhir': 'Bahrain',
  'Jeddah': 'Saudi_Arabia',
  'Miami': 'Miami',
  'Montreal': 'Canada',
  'Monte Carlo': 'Monaco',
  'Catalunya': 'Spain',
  'Spielberg': 'Austria',
  'Silverstone': 'Great Britain',
  'Spa-Francorchamps': 'Belgium',
  'Hungaroring': 'Hungary',
  'Zandvoort': 'Netherlands',
  'Monza': 'Italy',
  'Baku': 'Azerbaijan',
  'Singapore': 'Singapore',
  'Austin': 'USA',
  'Mexico City': 'Mexico',
  'Interlagos': 'Brazil',
  'Las Vegas': 'Las Vegas',
  'Lusail': 'Qatar',
  'Yas Marina Circuit': 'Abu Dhabi',
}

const slug = (s: string) =>
  s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')

const url = (name: string) =>
  `https://media.formula1.com/image/upload/f_auto,c_limit,w_1600,q_auto/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/${encodeURIComponent(name)}.jpg`

const SOURCES: Record<string, { url: string; extension: 'jpg' | 'webp' }> = {
  ...Object.fromEntries(
    Object.entries(RACEHUB_NAMES).map(([circuit, name]) => [circuit, { url: url(name), extension: 'jpg' as const }])
  ),
  // Actual circuit photograph supplied by Madring, published 2026-08-19:
  // https://www.formula1.com/en/latest/article/gallery-madring-circuit-shares-new-photos-ahead-of-madrids-maiden-grand-prix.vTxESDb75rcZnMyPrf9Ul
  Madring: {
    url: 'https://media.formula1.com/image/upload/t_16by9Centre/c_fit,w_1600,h_900/q_auto/v1740000001/fom-website/2026/Spain%20(Madrid)/YDRAY-YDRAY-DD86951D-3FCB-40E5-90AC-381DEA39370E-1.webp',
    extension: 'webp',
  },
  // OpenF1 calls Sepang "Kuala Lumpur". Match the circuit, not the event's
  // Bahrain country label. Official F1 announcement and aerial photograph:
  // https://corp.formula1.com/formula-1-and-fia-confirm-that-malaysia-will-join-the-2026-calendar-as-host-venue-for-the-bahrain-grand-prix/
  'Kuala Lumpur': {
    url: 'https://corp.formula1.com/wp-content/uploads/2026/07/Sepang-Circuit-Malaysia-1536x1024.jpg',
    extension: 'jpg',
  },
}

async function main() {
  const selected = process.argv.slice(2)
  for (const circuit of selected) {
    if (!SOURCES[circuit]) throw new Error(`Unknown circuit: ${circuit}`)
  }
  await mkdir(OUT, { recursive: true })
  // Preserve previously downloaded photos if an upstream source is unavailable.
  const paths: Record<string, string> = { ...CIRCUIT_PHOTOS }
  const missing: string[] = []
  for (const [circuit, source] of Object.entries(SOURCES)) {
    if (selected.length && !selected.includes(circuit)) continue
    try {
      const res = await fetch(source.url, { headers: { 'User-Agent': 'lights-out-site/1.0' } })
      if (!res.ok) {
        console.log(`MISS ${circuit} (${res.status})`)
        missing.push(circuit)
        continue
      }
      const buf = Buffer.from(await res.arrayBuffer())
      if (buf.length < 10000) {
        console.log(`MISS ${circuit} (tiny ${buf.length}b)`)
        missing.push(circuit)
        continue
      }
      const file = `${slug(circuit)}.${source.extension}`
      await writeFile(path.join(OUT, file), buf)
      paths[circuit] = `/media/circuit-photos/${file}`
      console.log(`OK   ${circuit} (${Math.round(buf.length / 1024)}KB)`)
    } catch (err) {
      console.log(`MISS ${circuit} (${(err as Error).message})`)
      missing.push(circuit)
    }
    await new Promise((r) => setTimeout(r, 200))
  }

  const manifest = `// GENERATED by scripts/fetch-circuit-photos.ts — do not edit by hand.
// Refresh with: npm run fetch-circuit-photos
// Official Formula 1 circuit photography, keyed by circuit_short_name.
// Source URLs and attribution: scripts/fetch-circuit-photos.ts.
// Circuits absent here (no photo upstream) fall back to line art.

export const CIRCUIT_PHOTOS: Record<string, string> = ${JSON.stringify(paths, null, 2)}

export const circuitPhoto = (circuitShortName: string): string | null =>
  CIRCUIT_PHOTOS[circuitShortName] ?? null
`
  await writeFile(path.join(ROOT, 'lib', 'circuit-photos-manifest.ts'), manifest)
  console.log(`\nTOTAL: ${Object.keys(paths).length}/${Object.keys(SOURCES).length} photos`)
  if (missing.length) console.log('missing:', missing.join(', '))
}

main()
