/**
 * Regenerate lib/roster-fallback.ts — the committed last-known slug list
 * that generateStaticParams falls back to when its data source is poisoned.
 *
 * Run when the roster changes (new driver, team rename):
 *   npx tsx scripts/sync-roster.ts
 *
 * Reads the LIVE production bundle rather than computing locally, because
 * production is the same snapshot the build would have used on a good day.
 */
import { writeFile } from 'node:fs/promises'
import path from 'node:path'
import { teamToSlug } from '../lib/team-data'
import { isCancelled } from '../lib/openf1'

const SOURCE = process.env.ROSTER_SOURCE ?? 'https://f1-website-three.vercel.app/api/season-data'

async function main() {
  const res = await fetch(SOURCE, { headers: { 'User-Agent': 'lights-out-site/1.0' } })
  if (!res.ok) throw new Error(`roster source ${res.status} — refusing to write a partial list`)
  const ct = res.headers.get('content-type') ?? ''
  if (!ct.includes('application/json')) {
    throw new Error(`roster source returned ${ct} (challenge page? SSO wall?) — refusing to write`)
  }
  const bundle = await res.json()
  if (bundle.blocked) throw new Error('roster source is a blocked placeholder — refusing to write')

  const drivers: string[] = [...new Set<string>(
    (bundle.driverStandings ?? []).map((d: { nameAcronym: string }) => d.nameAcronym.toUpperCase())
  )].sort()
  const teams: string[] = [...new Set<string>(
    (bundle.teamStandings ?? []).map((t: { teamName: string }) => teamToSlug(t.teamName))
  )].sort()

  // The share card's STATIC half. A card needs a number, a name, a team and
  // a livery colour; only the position/points line needs a live compute. So
  // that half is snapshotted here alongside the slugs, from the same source
  // and under the same plausibility guard — which is what lets a card
  // degrade by dropping one line instead of collapsing to a wordmark.
  const cards = (bundle.driverStandings ?? [])
    .map((d: Record<string, unknown>) => ({
      acronym: String(d.nameAcronym ?? '').toUpperCase(),
      number: Number(d.driverNumber ?? 0),
      first: String(d.firstName ?? ''),
      surname: String(d.surname ?? ''),
      team: String(d.teamName ?? ''),
      colour: String(d.teamColour ?? 'F5F5F3'),
    }))
    .filter((d: { acronym: string; number: number }) => d.acronym && d.number)
    .sort((a: { acronym: string }, b: { acronym: string }) => a.acronym.localeCompare(b.acronym))

  // The CALENDAR, snapshotted for the same reason as the cards: the round
  // that a shared /schedule link is about is a published fact months in
  // advance, so it has no business depending on a live compute at build
  // time. Numbering is computed here, once, over the scored rounds — the
  // route must not renumber a filtered subset.
  const calendar = (bundle.meetings ?? [])
    .filter((m: Record<string, unknown>) => {
      const n = String(m.meeting_name ?? '').toLowerCase()
      return !n.includes('testing') && !n.includes('pre-season') && !isCancelled(m)
    })
    .sort(
      (a: Record<string, unknown>, b: Record<string, unknown>) =>
        +new Date(String(a.date_start)) - +new Date(String(b.date_start))
    )
    .map((m: Record<string, unknown>, i: number) => ({
      round: i + 1,
      name: String(m.meeting_name ?? ''),
      circuit: String(m.circuit_short_name ?? ''),
      start: String(m.date_start ?? ''),
      end: String(m.date_end ?? ''),
    }))
    .filter((r: { circuit: string; start: string }) => r.circuit && r.start)

  if (drivers.length < 20 || teams.length < 10 || calendar.length < 15) {
    throw new Error(
      `implausible roster (${drivers.length} drivers, ${teams.length} teams, ${calendar.length} rounds) — refusing to write`
    )
  }

  const out = `// GENERATED by scripts/sync-roster.ts — re-run when the roster changes.
//
// The LAST-KNOWN-GOOD slug list. generateStaticParams falls back to this
// when the season bundle it reads is empty or implausible, so a poisoned
// data source (bot-challenge HTML, an SSO redirect, a rate-limited
// fallback) degrades to slightly stale slugs instead of silently
// prerendering nothing. ISR still fetches fresh data at request time — only
// the SET OF PAGES comes from here.
//
// Snapshot taken: ${new Date().toISOString().slice(0, 10)}

export const FALLBACK_DRIVER_ACRONYMS: readonly string[] = ${JSON.stringify(drivers, null, 2)}

export const FALLBACK_TEAM_SLUGS: readonly string[] = ${JSON.stringify(teams, null, 2)}

/**
 * Enough to draw a share card WITHOUT the season compute: number, name,
 * team and livery. Social platforms cache an OG image on first fetch and
 * never re-read it, so a card baked during a failed compute would sit in
 * Slack and X caches for weeks — "ISR heals it" is not true from the
 * sharer's side. With this, a failed compute costs the card its
 * position/points line and nothing else.
 */
export interface FallbackDriverCard {
  acronym: string
  number: number
  first: string
  surname: string
  team: string
  colour: string
}

export const FALLBACK_DRIVER_CARDS: readonly FallbackDriverCard[] = ${JSON.stringify(cards, null, 2)}

/** Scored rounds, already numbered. See FALLBACK_DRIVER_CARDS. */
export interface FallbackRound {
  round: number
  name: string
  circuit: string
  start: string
  end: string
}

export const FALLBACK_CALENDAR: readonly FallbackRound[] = ${JSON.stringify(calendar, null, 2)}
`
  await writeFile(path.join(__dirname, '..', 'lib', 'roster-fallback.ts'), out)
  console.log(`roster-fallback.ts written: ${drivers.length} drivers, ${teams.length} teams, ${calendar.length} rounds`)
}

main()
