/**
 * Regenerate lib/roster-fallback.ts — the committed last-known slug list
 * that generateStaticParams falls back to when its data source is poisoned.
 *
 * Run when the roster changes (new driver, team rename):
 *   npx tsx scripts/sync-roster.ts
 *
 * Reads the LIVE production bundle rather than computing locally, because
 * production is the same snapshot the build would have used on a good day.
 */
import { writeFile } from 'node:fs/promises'
import path from 'node:path'
import { teamToSlug } from '../lib/team-data'

const SOURCE = process.env.ROSTER_SOURCE ?? 'https://f1-website-three.vercel.app/api/season-data'

async function main() {
  const res = await fetch(SOURCE, { headers: { 'User-Agent': 'lights-out-site/1.0' } })
  if (!res.ok) throw new Error(`roster source ${res.status} — refusing to write a partial list`)
  const ct = res.headers.get('content-type') ?? ''
  if (!ct.includes('application/json')) {
    throw new Error(`roster source returned ${ct} (challenge page? SSO wall?) — refusing to write`)
  }
  const bundle = await res.json()
  if (bundle.blocked) throw new Error('roster source is a blocked placeholder — refusing to write')

  const drivers: string[] = [...new Set<string>(
    (bundle.driverStandings ?? []).map((d: { nameAcronym: string }) => d.nameAcronym.toUpperCase())
  )].sort()
  const teams: string[] = [...new Set<string>(
    (bundle.teamStandings ?? []).map((t: { teamName: string }) => teamToSlug(t.teamName))
  )].sort()

  if (drivers.length < 20 || teams.length < 10) {
    throw new Error(`implausible roster (${drivers.length} drivers, ${teams.length} teams) — refusing to write`)
  }

  const out = `// GENERATED by scripts/sync-roster.ts — re-run when the roster changes.
//
// The LAST-KNOWN-GOOD slug list. generateStaticParams falls back to this
// when the season bundle it reads is empty or implausible, so a poisoned
// data source (bot-challenge HTML, an SSO redirect, a rate-limited
// fallback) degrades to slightly stale slugs instead of silently
// prerendering nothing. ISR still fetches fresh data at request time — only
// the SET OF PAGES comes from here.
//
// Snapshot taken: ${new Date().toISOString().slice(0, 10)}

export const FALLBACK_DRIVER_ACRONYMS: readonly string[] = ${JSON.stringify(drivers, null, 2)}

export const FALLBACK_TEAM_SLUGS: readonly string[] = ${JSON.stringify(teams, null, 2)}
`
  await writeFile(path.join(__dirname, '..', 'lib', 'roster-fallback.ts'), out)
  console.log(`roster-fallback.ts written: ${drivers.length} drivers, ${teams.length} teams`)
}

main()
