'use client'
import { useCallback, useEffect, useRef, useState } from 'react'
import Link from 'next/link'
import { CALLS, CALL_INFO, emptyTicket, type Ticket } from '@/lib/predictions/game'
import { ROLE_INFO, money } from '@/lib/fantasy/rules'
import { ROLES, type Lineup } from '@/lib/fantasy/types'
import { type Game, type Weekend, type LiveEntry, type LiveScore, type liveCup } from '@/lib/games/competition'

type Board = { playerId:string; season:number; serverTime:string; weekends:Weekend[]; entries:LiveEntry[]; scores:LiveScore[]; leagues:{id:string; name:string; game:Game; owner_id:string; invite_code:string}[]; standings:{player_id:string; display_name:string; points:number; played:number; rank:number}[]; cups:NonNullable<ReturnType<typeof liveCup>>[] }
export default function CompetitionClient({game,connected,signedIn}:{game:Game;connected:boolean;signedIn:boolean}) {
  const requestId=useRef(0)
  const [data,setData]=useState<Board|null>(null),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
  const [league,setLeague]=useState(''),[selected,setSelected]=useState(''),[now,setNow]=useState(0),[offset,setOffset]=useState(0)
  const [lineup,setLineup]=useState<Lineup>({leader:'',charger:'',rival:''}),[ticket,setTicket]=useState<Ticket>(emptyTicket())
  const [leagueName,setLeagueName]=useState(''),[invite,setInvite]=useState('')
  const refresh=useCallback(async()=>{
    if(!signedIn) return
    const id=++requestId.current
    try {
      const response=await fetch(`/api/play?game=${game}${league?`&league=${league}`:''}`,{cache:'no-store'}),result=await response.json()
      if(id!==requestId.current)return
      if(!response.ok) throw new Error(result.error)
      setData(result);setOffset(Date.parse(result.serverTime)-Date.now());setNow(Date.parse(result.serverTime))
      setSelected(current=>result.weekends.some((w:Weekend)=>w.id===current)?current:result.weekends.find((w:Weekend)=>w.status==='open' && Date.parse(w.locks_at)>Date.parse(result.serverTime))?.id ?? result.weekends.at(-1)?.id ?? '')
    } catch(e) {setNotice(e instanceof Error?e.message:'Unable to load competition.')}
  },[game,league,signedIn])
  useEffect(()=>{void refresh()},[refresh])
  useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()+offset),1000);return()=>clearInterval(timer)},[offset])
  const weekend=data?.weekends.find(w=>w.id===selected), entry=data?.entries.find(e=>e.weekend_id===selected)
  const saved=entry?JSON.stringify(entry.payload):''
  useEffect(()=>{const payload=saved?JSON.parse(saved):null;if(game==='fantasy')setLineup(payload?.lineup??{leader:'',charger:'',rival:''});else setTicket(payload??emptyTicket())},[selected,saved,game])
  const closed=!weekend || weekend.status!=='open' || now>=Date.parse(weekend.locks_at)
  const cost=weekend?ROLES.reduce((n,r)=>n+(weekend.roster.find(d=>d.id===lineup[r])?.price??0),0):0
  const remaining=weekend?Math.max(0,Math.ceil((Date.parse(weekend.locks_at)-now)/1000)):0
  const deadline=remaining>=86400?`${Math.floor(remaining/86400)}d ${Math.floor(remaining%86400/3600)}h`:remaining>=3600?`${Math.floor(remaining/3600)}h ${Math.floor(remaining%3600/60)}m`:`${Math.floor(remaining/60)}m ${remaining%60}s`
  const selectedLeague=data?.leagues.find(l=>l.id===league)
  async function action(body:Record<string,unknown>) {
    setBusy(true);setNotice('')
    try {const response=await fetch('/api/play',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),result=await response.json();if(!response.ok)throw new Error(result.error);await refresh();setNotice(body.action==='entry'?'Entry saved on the server. You can edit it until the deadline.':body.action==='rotate'?'New invite code created. The previous code no longer works.':'Your league membership is ready.');return true}
    catch(e){setNotice(e instanceof Error?e.message:'Please retry.');return false}finally{setBusy(false)}
  }
  const playerName=(id:string|null)=>id?data?.standings.find(p=>p.player_id===id)?.display_name??'League member':'Bye'
  return <div className={`online-game online-game--${game}`}><div className="online-top"><Link href={`/${game}`}>← Back to practice</Link><Link href="/account">My paddock ↗</Link></div><header><span className="online-label">LIGHTS OUT / {game.toUpperCase()} ONLINE</span><h1>{game==='fantasy'?<>THE REAL <em>RIVALRY.</em></>:<>CALL IT.<br /><em>PROVE IT.</em></>}</h1><p>{game==='fantasy'?'Your squad against real players. Season points and private-league knockout cups.':'One weekend. Six calls. A prediction championship of its own.'}</p></header>
    {!connected || !signedIn ? <section className="online-gate"><span className="online-label">{connected?'YOUR PLACE IS WAITING':'THE GRID IS GETTING READY'}</span><h2>{connected?'TAKE YOUR PLACE.':'REAL RIVALS. COMING NEXT.'}</h2><p>{connected?'Sign in to enter real weekends, save across devices and bring friends into a private league.':'Online accounts are being connected. Your practice progress stays available while the real-player grid is prepared.'}</p><Link className="online-button" href={`/login?next=/play/${game}`}>{connected?'Enter the paddock':'Preview the paddock pass'} ↗</Link><Link className="online-link" href={`/${game}`}>Continue practice ↗</Link></section> : <>
      <p className="online-notice" role="status">{notice}</p>
      {!data && <button className="online-button" onClick={refresh}>Reload competition</button>}
      {data && <><div className="online-controls"><label>Race weekend<select value={selected} onChange={e=>setSelected(e.target.value)} disabled={!data.weekends.length}>{!data.weekends.length && <option>No published weekends</option>}{data.weekends.map(w=><option key={w.id} value={w.id}>R{w.round} · {w.name}{w.status==='final'?' · Final':w.status==='cancelled'?' · Cancelled':''}</option>)}</select></label><button className="online-link" disabled={busy} onClick={refresh}>Refresh results ↗</button></div>
      {!weekend?<div className="online-gate"><h2>THE NEXT GRID IS BEING SET.</h2><p>Entries open when the race weekend, eligible drivers and qualifying deadline have been published. You can create your private league now.</p></div>:<section className="online-weekend"><div className="online-deadline"><div><span className="online-label">ROUND {weekend.round} / {weekend.name}</span><h2>{weekend.status==='final'?'THE RESULTS ARE IN.':closed?'THE GRID IS LOCKED.':'MAKE YOUR MOVE.'}</h2><p>Locks at the start of Grand Prix qualifying: {new Date(weekend.locks_at).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'})} (your time).</p><small>Confirmed by the server. Sprint qualifying does not set this deadline.</small></div><div><span>{closed?'ENTRY STATUS':'TIME TO LOCK'}</span><strong>{closed?entry?'SAVED':'NO ENTRY':deadline}</strong></div></div>
        <form onSubmit={e=>{e.preventDefault();void action({action:'entry',game,weekend:weekend.id,payload:game==='fantasy'?{lineup}:ticket})}}>
          {game==='fantasy'?<><div className="online-picks">{ROLES.map((role,i)=><label key={role}><span className="online-pick-number">0{i+1}</span><strong>{ROLE_INFO[role].name}</strong><select required disabled={closed||busy} value={lineup[role]} onChange={e=>setLineup({...lineup,[role]:e.target.value})}><option value="">Choose driver</option>{weekend.roster.map(d=><option key={d.id} value={d.id}>{d.surname} · {money(d.price)}</option>)}</select><small>{ROLE_INFO[role].rule}</small></label>)}</div><p className="online-budget">Squad cost <strong>{money(cost)}</strong> / {money(weekend.budget)} budget</p></>:<><div className="online-picks">{CALLS.map((call,i)=><label key={call}><span className="online-pick-number">0{i+1}</span><strong>{CALL_INFO[call].label}</strong><select required disabled={closed||busy} value={ticket.picks[call]??''} onChange={e=>setTicket({...ticket,picks:{...ticket.picks,[call]:e.target.value}})}><option value="">Make the call</option>{call==='safety'?<><option value="yes">Yes · Full safety car</option><option value="no">No full safety car</option></>:weekend.roster.map(d=><option key={d.id} value={d.id}>{d.surname}</option>)}</select><small>{CALL_INFO[call].points} points · {CALL_INFO[call].description}</small></label>)}</div><label className="online-boost">Your ×2 confidence call<select required disabled={closed||busy} value={ticket.boost??''} onChange={e=>setTicket({...ticket,boost:e.target.value as Ticket['boost']})}><option value="">Choose one call to double</option>{CALLS.map(call=><option key={call} value={call}>{CALL_INFO[call].label}</option>)}</select></label></>}
          <div className="online-entry-actions"><button className="online-button" disabled={closed||busy}>{busy?'Saving…':entry?'Update my entry ↗':'Save my entry ↗'}</button><p>{entry?`Server save: ${new Date(entry.updated_at).toLocaleString()}`:closed?'No entry was saved for this weekend.':'Your picks stay private until the deadline. Save before leaving this page.'}</p></div>
        </form>
        {weekend.status==='final' && <div className="online-receipt"><h3>YOUR WEEKEND RECEIPT</h3><strong>{data.scores.find(s=>s.weekend_id===weekend.id)?.points??0}<small> PTS</small></strong><p>{entry?'Scored from published final results.':'No entry, no points this weekend.'} Result version {weekend.result_version}.</p><details><summary>How this weekend was scored</summary>{game==='fantasy'?<p>Qualifying P1–P10 earns 10–1 points; race P1–P10 earns 25, 18, 15, 12, 10, 8, 6, 4, 2, 1. Finish +2, DNF −5, DSQ −10. Your three role bonuses are listed above. DNS earns qualifying points only.</p>:<p>Exact calls earn the listed award. A podium driver in another place earns 5. Your confidence call doubles its award, including partial credit. Tied biggest movers all count; only race finishers qualify. Virtual safety cars do not count.</p>}{(() => {const score=data.scores.find(s=>s.weekend_id===weekend.id)?.breakdown as {drivers?:{driverId:string;total:number;lines:{label:string;points:number}[]}[];calls?:{call:string;picked:string;actual:string;total:number}[]}|undefined;return score?.drivers?<div className="online-score-details">{score.drivers.map(d=><div key={d.driverId}><h4>{d.driverId} · {d.total} pts</h4>{d.lines.map(l=><p key={l.label}>{l.label}<b>{l.points}</b></p>)}</div>)}</div>:score?.calls?<div className="online-score-details">{score.calls.map(c=><p key={c.call}>{c.call}: {c.picked} · result {c.actual}<b>{c.total}</b></p>)}</div>:null})()}</details></div>}
      </section>}
      <section className="online-leaderboard"><div className="online-section-title"><div><span className="online-label">{data.season} / {game.toUpperCase()}</span><h2>PUT YOUR NAME ON IT.</h2></div><label>Competition<select value={league} onChange={e=>setLeague(e.target.value)}><option value="">Global championship</option>{data.leagues.map(l=><option value={l.id} key={l.id}>{l.name}</option>)}</select></label></div><p>{league?'Your private league. All season points count, including weekends before joining.':'Real players only. The top 1,000 entries are shown.'} Equal season totals share a rank.</p><div data-scroll-x className="online-table-scroll"><table><thead><tr><th>POS</th><th>PLAYER</th><th>WEEKENDS</th><th>POINTS</th></tr></thead><tbody>{data.standings.map(p=><tr key={p.player_id} className={p.player_id===data.playerId?'is-you':''}><td>{String(p.rank).padStart(2,'0')}</td><th scope="row">{p.display_name}{p.player_id===data.playerId&&<small> YOU</small>}</th><td>{p.played}</td><td>{p.points}</td></tr>)}</tbody></table></div>{!data.standings.length&&<p className="online-empty">No players on this board yet. Save an entry to join the championship.</p>}
      {selectedLeague&&<div className="online-invite"><p>Invite friends to <strong>{selectedLeague.name}</strong>. Up to 16 players.</p><label>League invite code<input readOnly value={selectedLeague.invite_code} onFocus={e=>e.target.select()} /></label><button className="online-link" onClick={async()=>{try{await navigator.clipboard.writeText(selectedLeague.invite_code);setNotice('Invite code copied. Share it with your friends.')}catch{setNotice('Select the invite code and copy it manually.')}}}>Copy code</button>{selectedLeague.owner_id===data.playerId&&<button className="online-link" disabled={busy} onClick={()=>action({action:'rotate',league})}>Replace invite code</button>}</div>}
      {game==='fantasy'&&selectedLeague&&<section className="online-cups"><h3>THE KNOCKOUT FIGHT.</h3><p>Four race weekends per cup. Up to 16 players, seeded by season points before the first race. Membership locks with that race’s entries. Missing entries score zero; empty slots are byes. Ties use role bonuses, leader points, then seed. A cancelled race advances the higher seed. Later result corrections recalculate the bracket.</p>{!data.cups.length&&<p>Brackets appear after the first weekend’s deadline. Invite your rivals before it locks.</p>}{data.cups.map(cup=><div key={cup.number}><h4>CUP {cup.number}{cup.champion?` · ${playerName(cup.champion)} WINS`:''}</h4>{cup.seeds.length<2?<p>At least two members were needed at this cup’s opening deadline. The next cup is a fresh start.</p>:<div className="online-bracket" data-scroll-x>{cup.stages.map((stage,i)=><div key={i}><span className="online-label">{['ROUND OF 16','QUARTERFINAL','SEMIFINAL','FINAL'][i]}</span>{stage.filter(m=>m.a||m.b).map((m,j)=><article key={j}>{[m.a,m.b].map((id,k)=><p key={k} className={m.winner===id&&id?'is-winner':''}><span>{playerName(id)}</span><b>{k===0?m.pointsA??'—':m.pointsB??'—'}</b></p>)}<small>{m.cancelled?'Cancelled · seed decides':m.bye?'Bye':m.tiebreak?'Tiebreak applied':`Race ${m.round}`}</small></article>)}</div>)}</div>}</div>)}</section>}
      </section>
      <section className="online-leagues"><div><span className="online-label">BRING YOUR OWN RIVALRY</span><h2>A LEAGUE OF YOUR OWN.</h2><p>Invite friends with a private code. Fantasy and Predictions each have their own league and standings.</p></div><form onSubmit={async e=>{e.preventDefault();if(await action({action:'create',game,name:leagueName}))setLeagueName('')}}><label>New {game} league<input required minLength={2} maxLength={32} placeholder="Your league name" value={leagueName} onChange={e=>setLeagueName(e.target.value)} /></label><button className="online-button" disabled={busy}>Create league ↗</button></form><form onSubmit={async e=>{e.preventDefault();if(await action({action:'join',code:invite.trim()}))setInvite('')}}><label>Have an invite?<input required placeholder="Paste invite code" value={invite} onChange={e=>setInvite(e.target.value)} /></label><button className="online-button" disabled={busy}>Join league ↗</button></form></section>
      </>}
    </>}<footer className="online-footer"><p>Free to play. No wagers or cash prizes. Practice results never enter these standings.</p><Link href={`/play/${game==='fantasy'?'predictions':'fantasy'}`}>Explore {game==='fantasy'?'Predictions':'Fantasy'} ↗</Link></footer></div>
}
